# Site settings
title: Jayson Blasko
description: > # this means to ignore newlines until "baseurl:"
  Jayson Blasko Portfolio Website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jaysonblasko.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
